spring.application.name=build-wise

spring.datasource.url=jdbc:postgresql://localhost:5432/build-wise
spring.datasource.username=build_user
spring.datasource.password=build_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.upload-dir=uploads
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB